Repository yes-ee/irc, pull requests merged in 2023-10, with the labels that each got.

#29 ✨feat: invite
  flow.sh
  inc/Server.hpp
  src/Server.cpp
Labels: ✨ Feature

#30 ✨feat: kick method
  inc/Server.hpp
  src/Channel.cpp
  src/Server.cpp
Labels: ✨ Feature

#31 🔨fix: merge code and fix invite
  inc/Channel.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Server.cpp
Labels: 🐞 Bug

#32 🔨 fix: merge everything
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
Labels: 🐞 Bug, ✨ Feature

#34 Fix/merge
  Makefile
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
  test_leaks.sh
Labels: 🐞 Bug, ✨ Feature, 🎨 Refactor

#35 🔨 fix: nc quit
  src/Client.cpp
  src/Server.cpp
Labels: 🐞 Bug, 🎨 Refactor
