Repository yes-ee/irc, pull requests merged in 2023-09, with the labels that each got.

#1 ✨feat: irc structure
  .gitignore
  Makefile
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
Labels: ✨ Feature

#5 Update README.md
  README.md
Labels: 📝 Docs

#6 ✨feat: method parsing
  inc/Client.hpp
  inc/Server.hpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#9 ✨feat: CRLF parsing 및 response prefix 설정
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#10 ✨ feat: PASS method
  .gitignore
  Makefile
  inc/Client.hpp
  inc/Server.hpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
Labels: ✨ Feature

#11 ✨feat: response macro
  inc/Client.hpp
  inc/Server.hpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#16 Update README.md
  README.md
Labels: 📝 Docs

#15 ✨feat: join method
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#17 ✨feat: chatting
  inc/Client.hpp
  inc/Server.hpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#18 ✨feat: quit
  flow.sh
  inc/Channel.hpp
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#19 🔨 fix: chatting
  inc/Server.hpp
  src/Server.cpp
Labels: 🎨 Refactor

#20 🔨 fix: msg white space problem
  src/Server.cpp
Labels: 🐞 Bug

#21 ✨ feat: quit method 나갈 때 broadcasting
  src/Server.cpp
Labels: ✨ Feature

#22 ✨feat : list method
  inc/Channel.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Server.cpp
Labels: ✨ Feature

#23 ✨feat: topic command
  inc/Channel.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Server.cpp
Labels: ✨ Feature

#24 ✨feat: who method
  .gitignore
  doc.txt
  flow.sh
  inc/Channel.hpp
  inc/Server.hpp
  init_docker.sh
  src/Server.cpp
Labels: ✨ Feature

#25 ✨feat: part method
  inc/Client.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
Labels: ✨ Feature

#27 🔨fix: msg exception
  inc/Server.hpp
  src/Server.cpp
Labels: 🎨 Refactor

#28 🔨 fix: pass method - duplicate error msg
  inc/Client.hpp
  src/Client.cpp
  src/Server.cpp
Labels: 🐞 Bug
